// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BaseModel interface {
	IsBaseModel()
	GetID() string
	GetTitle() string
	GetSlug() *string
	GetCreatedAt() *int
	GetUpdatedAt() *int
}

type NewTask struct {
	Title string `json:"title"`
	Note  string `json:"note"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateTask struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Note  string `json:"note"`
}
