// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BaseModel interface {
	IsBaseModel()
	GetID() string
	GetTitle() string
	GetSlug() *string
	GetCreatedAt() *int
	GetUpdatedAt() *int
}

type NewTask struct {
	Title string `json:"title"`
	Note  string `json:"note"`
}

type NewUser struct {
	Username  string `json:"username"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Password1 string `json:"password1"`
	Password2 string `json:"password2"`
}

type UpdateTask struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Note  string `json:"note"`
}

type UpdateUser struct {
	Name        string  `json:"name"`
	Email       string  `json:"email"`
	Phone       string  `json:"phone"`
	OldPassword *string `json:"oldPassword"`
	NewPassword *string `json:"newPassword"`
}
