// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthOps struct {
	Login    interface{} `json:"login"`
	Register interface{} `json:"register"`
}

type NewTask struct {
	Title string `json:"title"`
	Note  string `json:"note"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}



type TaskMutation struct {
	CreateTask *Task `json:"createTask"`
	UpdateTask *Task `json:"updateTask"`
	DeleteTask bool  `json:"deleteTask"`
}

type UpdateTask struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Note  string `json:"note"`
}
